# this is an autogenerated file - does not try to modify it manually, use the character editor instead!
class_name GameCharacters 
 
# A list of all characters
enum Characters{
Several_Code,
Enemy_A,
Enemy_B,
}

# A dictionary containing the characters identifiers associated to the character enumaration
const characters_map = {
Characters.Several_Code : "1469ea5b-4647-495b-ba0a-6c038153a639",
Characters.Enemy_A : "a7c2ce70-3edd-42dc-875c-809a93c5c954",
Characters.Enemy_B : "d26cf9dd-8d11-49c8-a578-9c5573b8b5d0",
}
