# this is an autogenerated file - does not try to modify it manually, use the character editor instead!
class_name GameCharacters 
 
# A list of all characters
enum Characters{
SeveralCode,
Blacksmith,
Artisan,
Player,
}

# A dictionary containing the characters identifiers associated to the character enumaration
const characters_map = {
Characters.SeveralCode : "d8f5354f-e744-4774-beff-024671e6e1e3",
Characters.Blacksmith : "6a039f7b-1332-4450-bc63-37a2dfe00ed5",
Characters.Artisan : "b036d5f2-e6fe-43e2-a071-3dbe636eb409",
Characters.Player : "6869fdbf-9ee1-4b3f-980f-a44763ddde73",
}
